# Generated by Django 3.2.9 on 2021-11-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_flight_booking_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightdescription',
            options={'ordering': ['flightNumber']},
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
