# Generated by Django 3.2.9 on 2021-11-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_flight_booking_api', '0002_auto_20211114_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dastugo_flight_booking_api.passenger'),
        ),
    ]
