# Generated by Django 3.2.9 on 2021-11-13 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dastugo_flight_booking_api', '0003_auto_20211114_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
